//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.10 at 05:37:34 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.soap.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soap.interfaces;
